DROP TABLE IF EXISTS group_child_star;

CREATE VIEW IF NOT EXISTS group_child_star AS WITH RECURSIVE GCS(P,C) AS ( SELECT ID AS P, ID AS C FROM SUB_GROUP UNION ALL SELECT GCS.P AS P, GROUP_CHILD.CHILD_ID AS C FROM GCS JOIN GROUP_CHILD ON GCS.C=GROUP_CHILD.PARENT_ID ) SELECT DISTINCT GCS.P AS parent, GCS.C as child FROM GCS;
