'use strict';

const USER_SERVICE = "/rest/user";
const GET_LOGGED_IN_USER = USER_SERVICE + "/getlogged";
const USER_SERVICE_USERS_READ = USER_SERVICE + "/readUsers";
const USER_SERVICE_USERS_READ_DETAIL = USER_SERVICE + "/readUserDetail";
const USER_SERVICE_USERS_UPDATE_PERMS = USER_SERVICE + "/updatePerms";
const USER_SERVICE_MODERATORS_READ = USER_SERVICE + "/readMods";
const USER_SERVICE_MODERATORS_READ_DETAIL = USER_SERVICE + "/readModDetail";
const USER_SERVICE_MODERATORS_UPDATE_SUBSCRIBE = USER_SERVICE +"/updateModSub"

const MAIL_SERVICE = "/rest/mail";
const GET_MAIL_SETTINGS = MAIL_SERVICE + "/getmailset";
const SET_MAIL_SETTINGS = MAIL_SERVICE + "/setmailset";

const SOURCE_SERVICE = "/rest/source";
const SOURCE_SERVICE_READ = SOURCE_SERVICE + "/read"
const SOURCE_SERVICE_CREATE = SOURCE_SERVICE + "/create"
const SOURCE_SERVICE_READ_DETAIL = SOURCE_SERVICE + "/readDetail"
const SOURCE_SERVICE_SAVE_DETAIL = SOURCE_SERVICE + "/saveDetail"
const SOURCE_SERVICE_UPDATE_SUBSCRIBE = SOURCE_SERVICE + "/updateSub"
const SOURCE_SERVICE_READ_ATTRIBUTES = SOURCE_SERVICE + "/readAttr"
const SOURCE_SERVICE_SAVE_ATTRIBUTES = SOURCE_SERVICE + "/saveAttr"

const GROUP_SERVICE = "/rest/group";
const GROUP_SERVICE_READ = GROUP_SERVICE + "/read"
const GROUP_SERVICE_CREATE = GROUP_SERVICE + "/create"
const GROUP_SERVICE_READ_DETAIL = GROUP_SERVICE + "/readDetail"
const GROUP_SERVICE_SAVE_DETAIL = GROUP_SERVICE + "/saveDetail"
const GROUP_SERVICE_UPDATE_SUBSCRIBE = GROUP_SERVICE + "/updateSub"
const GROUP_SERVICE_UPDATE_CHILDREN = GROUP_SERVICE + "/updateChild"
const GROUP_SERVICE_UPDATE_SOURCES = GROUP_SERVICE + "/updateSource"
const GROUP_SERVICE_UPDATE_POSTERS = GROUP_SERVICE + "/updatePoster"

const POST_SERVICE = "/rest/post";
const POST_SERVICE_READ = POST_SERVICE + "/read"
const POST_SERVICE_CREATE = POST_SERVICE + "/create"
const POST_SERVICE_READ_DETAIL = POST_SERVICE + "/readDetail"

export {
	GET_LOGGED_IN_USER,
	USER_SERVICE_USERS_READ,
	USER_SERVICE_USERS_READ_DETAIL,
	USER_SERVICE_USERS_UPDATE_PERMS,
	USER_SERVICE_MODERATORS_READ,
	USER_SERVICE_MODERATORS_READ_DETAIL,
	USER_SERVICE_MODERATORS_UPDATE_SUBSCRIBE,
	GET_MAIL_SETTINGS,
	SET_MAIL_SETTINGS,
	SOURCE_SERVICE_READ,
	SOURCE_SERVICE_CREATE,
	SOURCE_SERVICE_READ_DETAIL,
	SOURCE_SERVICE_SAVE_DETAIL,
	SOURCE_SERVICE_UPDATE_SUBSCRIBE,
	SOURCE_SERVICE_READ_ATTRIBUTES,
	SOURCE_SERVICE_SAVE_ATTRIBUTES,
	GROUP_SERVICE_READ,
	GROUP_SERVICE_CREATE,
	GROUP_SERVICE_READ_DETAIL,
	GROUP_SERVICE_SAVE_DETAIL,
	GROUP_SERVICE_UPDATE_SUBSCRIBE,
	GROUP_SERVICE_UPDATE_CHILDREN,
	GROUP_SERVICE_UPDATE_SOURCES,
	GROUP_SERVICE_UPDATE_POSTERS,
	POST_SERVICE_READ,
	POST_SERVICE_CREATE,
	POST_SERVICE_READ_DETAIL,
};